### ISSUE TITLE
No URLs found in the file.

### ISSUE THREAD

**Issue by linhcentrio** [BB31420/loveListLace#1]
(venv) D:\loveListLace>python main.py
Fetching data from URL: https://sfbay.craigslist.org/jsonsearch/cto?query=You+are+a+used+cars+salesman.+Do+not+speak+as+if+the+subjects+in+the+stories+are+listening.+Do+not+repeat+yourself,+be+interesting+but+not+long-winded.+Do+not+use+[Your+Name]+instead+create+a+real+name+you+prefer.+Do+not+repeat+a+website+url.
&srchType=A&hasPic=0&bundleDuplicates=1&format=json
URLs saved to SF bay area_cto_urls.json
No URLs found in the file.
No URLs file found for selected area and category.
Fetching data from URL: https://seattle.craigslist.org/jsonsearch/cto?query=You+are+a+used+cars+salesman.+Do+not+speak+as+if+the+subjects+in+the+stories+are+listening.+Do+not+repeat+yourself,+be+interesting+but+not+long-winded.+Do+not+use+[Your+Name]+instead+create+a+real+name+you+prefer.+Do+not+repeat+a+website+url.
&srchType=A&hasPic=0&bundleDuplicates=1&format=json
URLs saved to seattle-tacoma_cto_urls.json
Fetching data from URL: https://newyork.craigslist.org/jsonsearch/cto?query=You+are+a+used+cars+salesman.+Do+not+speak+as+if+the+subjects+in+the+stories+are+listening.+Do+not+repeat+yourself,+be+interesting+but+not+long-winded.+Do+not+use+[Your+Name]+instead+create+a+real+name+you+prefer.+Do+not+repeat+a+website+url.
&srchType=A&hasPic=0&bundleDuplicates=1&format=json
URLs saved to new york city_cto_urls.json
Fetching data from URL: https://enid.craigslist.org/jsonsearch/cto?query=You+are+a+used+cars+salesman.+Do+not+speak+as+if+the+subjects+in+the+stories+are+listening.+Do+not+repeat+yourself,+be+interesting+but+not+long-winded.+Do+not+use+[Your+Name]+instead+create+a+real+name+you+prefer.+Do+not+repeat+a+website+url.
&srchType=A&hasPic=0&bundleDuplicates=1&format=json
URLs saved to northwest OK_cto_urls.json
No URLs found in the file.

**Comment by BB31420** [comment]
![image](https://github.com/BB31420/loveListLace/assets/110313117/749f89a3-9379-4553-aa64-f7d190e14e68)

The URLs aren't being found due to the search query not returning any results.

In the query box on the main window, enter your search terms: honda, acura, bmw, ford, whichever you want to search for.

 The prompt to control how the AI responds to your search results is in the 'Generate OpenAI Response' window

**Comment by linhcentrio** [comment]
yes it work well done, but only one image it's not helpful to make better video

**Comment by BB31420** [comment]
thank you. good job getting it to work. feel free to modify the code to produce and then merge multiple images. 

the two generate video functions in the code can be changed to hard code the number of images according to your API rate limit for Dale-3 (5 per min for tier 1 or 1 per minute for free tier) 

you could also add UI elements to allow the user to set the number of images. if you need more than 5 images, you will need to introduce a wait time so you are only generating one image every 12 seconds to respect the API rate limit and avoid account issues.
