### ISSUE TITLE
error generate video

### ISSUE THREAD

**Issue by yekayee** [BB31420/loveListLace#2]
An error occurred while generating the video: MoviePy error: failed to read the duration of file SF bay area_mis_speech.mp3.
Here are the file infos returned by ffmpeg:

ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[mp3 @ 0000022090179a40] Format mp3 detected only with low score of 1, misdetection possible!
[mp3 @ 0000022090179a40] Failed to read frame size: Could not seek to 8115.
SF bay area_mis_speech.mp3: Invalid argument

**Comment by BB31420** [comment]
can you play the mp3 file in a media player to confirm it was generated properly by NeetsAI

**Comment by yekayee** [comment]
cant bro, how i fix it ?

**Comment by yekayee** [comment]
whats category for love story or kids story?

**Comment by BB31420** [comment]
https://github.com/BB31420/loveListLace/blob/main/categories.csv

Might be easier to read the categories here

Once you start with one category, go all the way through click each option in order
